// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX8bhDJ5F4DPI17MIHV28hlczvKpYwXXM',
    appId: '1:906271042039:web:e8356a947e6ea485cb66f2',
    messagingSenderId: '906271042039',
    projectId: 'flash-chat-b3faf',
    authDomain: 'flash-chat-b3faf.firebaseapp.com',
    storageBucket: 'flash-chat-b3faf.firebasestorage.app',
    measurementId: 'G-BHC4Y99B6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx1IkvB-jJ_eruhBLkxTsE5leF3n2GYrk',
    appId: '1:906271042039:android:59ef33f3dc385a97cb66f2',
    messagingSenderId: '906271042039',
    projectId: 'flash-chat-b3faf',
    storageBucket: 'flash-chat-b3faf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQgR2yqd0KiD0J_ogE1IJ3RtDTI3m4NAE',
    appId: '1:906271042039:ios:e7f655a3260c0376cb66f2',
    messagingSenderId: '906271042039',
    projectId: 'flash-chat-b3faf',
    storageBucket: 'flash-chat-b3faf.firebasestorage.app',
    iosBundleId: 'co.appbrewery.flashChat',
  );

}